# Generated by Django 6.1 on 2026-09-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='channel',
            field=models.CharField(blank=True, choices=[('gmail', 'Gmail'), ('calendar', 'Calendar'), ('slack', 'Slack'), ('banking', 'Banking'), ('contacts', 'Contacts')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='draft',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='expires_in_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='intent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='reasoning',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='recipient',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='side_effects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
